# This workflow will install Python dependencies, run tests and lint with multiple versions of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Lint and Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timetimeout-minutes: 5
    strategy:
      matrix:
        python-version: ["pypy3.10", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Install native dependencies
      run: |
        sudo apt-get install -y libdwarf-dev libelf-dev libiberty-dev linux-headers-generic libc6-dbg
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pwntools pytest ruff
    - name: Lint with Ruff
      run: |
        ruff check libdebug --output-format=github 
      continue-on-error: true
    - name: Install library
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd test && pytest --ignore=other_tests
